import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/navbar/navbar'
import Footer from '@/components/footer/footer'
import { Ingresso, IngressosProps } from '@/interfaces/interfaces'
import TipoIngresso from '@/components/tipoIngresso/tipoIngresso'
import Link from 'next/link';
import PhotoCard from '../components/photoCard/photoCard'
import HomeIngressoCard from '@/components/homeIngressoCard/homeIngressoCard'
import NavbarResponsivo from '@/components/NavbarResponsivo/NavbarResponsivo'
import imagem1 from '../../public/img/cardImage1.svg'
import imagem2 from '../../public/img/cardImage2.svg'
import imagem3 from '../../public/img/cardImage3.svg'
import imagem4 from '../../public/img/cardImage4.svg'
import imagem5 from '../../public/img/cardImage5.svg'
import imagem6 from '../../public/img/cardImage6.svg'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Navigation, Pagination, Scrollbar, A11y } from 'swiper/modules';
import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

// const repeatText = (text:string) => {
//   let screenWidth = screen.width;
//   let textWidth = text.length*8;
//   let repetitions = Math.ceil(screenWidth/textWidth);

//   let repeatText = Array(repetitions).fill(text);
  
//   return repeatText;

// }
const repeatText = (text: string) => {
  let screenWidth;
  if (typeof window !== "undefined") {
    screenWidth = screen.width;
  }
  let textWidth = text.length * 8;
  let repetitions = 10;

  let repeatedText = Array(repetitions).fill(text);

  return repeatedText;
};

  const imagensCarrossel1 = [imagem1,imagem2,imagem3]

  return (
    <>
      <Head>
        <title>Tokyo Festival</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.navbarDesktop}><Navbar/></header>
      {( // RESPONSIVO
            <div className={styles.navbarResponsivo}><NavbarResponsivo largura={700}/></div> 
        )}

      {/* Primeira seção */}
      <div className='background-container'>
        <section className='main-container'>
          <div className={styles.imgContainer}>
            <Image src="/img/japoneseTextBackground.svg" alt="Imagem de fundo de um texto em japonês" width={1000} height={300}/>
              <h3>Meltdown Fusion</h3>
              <h1>TOKYO</h1>
              <div className={styles.bShadow}>
            </div>  
          </div>
          {//Responsivo 
             <div className={styles.imgContainerResponsivo}>
             <Image src="/img/japoneseTextBackground.svg" alt="Imagem de fundo de um texto em japonês" width={850} height={250}/>
               <h3>Meltdown Fusion</h3>
               <h1>TOKYO</h1>
               <div className={styles.bShadow}>
             </div>  
           </div>
          }
          <div className={styles.bottomContent}>
            <h3>23/08/23 - 25/08/23</h3>
            <div className={styles.buyButton}>
            <Link href='/ingressos' legacyBehavior>
              <a>Compre o ingresso</a>
              </Link>
            </div>
          </div>
        </section>
      </div>

      {/* Seção Sobre Nós */}
      <div className='background-container'>
        <div className={styles.sectionTitle}>
         {
            repeatText('SOBRE NÓS ').map((text, index) => {
              if(index==1){
                return <span className={styles.span}>{text}</span>
              }
              else if(index ==0){
                let parts = text.split("O");
                return <h1>{parts[1]}</h1>
              }
              else{
                return <h1>{text}</h1>
              }
            })
          }
          </div>
        <section className='main-container'>
          <div className={styles.sobreNosContainerBox}>
            <div className={styles.sobreNosText}>
              <h2>Meltdow Fusion Tokyo</h2>
              <p>Rorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vulputate libero et velit interdum, ac aliquet odio mattis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</p>
              <Image className={styles.sobreNosJaponeseImage} src='/img/sobreNosJaponeseImage.svg' alt='Imagem de texto em japonês' width={450} height={126}/>
            </div>
            <div className={styles.sobreNosImageContainer}><Image src='/img/sobreNosImage.svg' alt='Imagem de um show ao vivo' width={653} height={544}/>
            <Image className={styles.layer} src='/img/Layer.svg' alt='Imagem de um show ao vivo' width={675} height={80}/>
            {
              <Image className={styles.layerResponsivo} src='/img/Layer.svg' alt='Imagem de um show ao vivo' width={675} height={80}/>
            }
            </div>
          </div>
        </section>
      </div>

      {/*Seção Principais Atrações*/}
      <div className='background-container'>
        <div className={styles.sectionTitle}>
          {
              repeatText('PRINCIPAISATRAÇÕES').map((text, index) => {
                if(index==1){
                  return <span className={styles.span}>{text}</span>
                }
                else if(index ==0){
                  let parts = text.split("A");
                  return <h1>{parts[2]+"A"+parts[3]}</h1>
                }
                else{
                  return <h1>{text} </h1>
                }
              })
            }

        </div>
        <section className='main-container'>
            <div className={styles.photoSectionBox}>
              <PhotoCard caminho='/img/cardImage1.svg' nome='MARCUS RHIEL' tipo={false} largura={400} altura={650}/>
              <PhotoCard caminho='/img/cardImage2.svg' nome='DULCE AMINOFF' tipo={false} largura={400} altura={650}/>
              <PhotoCard caminho='/img/cardImage3.svg' nome='RAYNA STANTON' tipo={false} largura={400} altura={650}/>
            </div>
            { // RESPONSIVO
              <div className={styles.carrossel}>
                <Swiper
                  modules={[Navigation, Pagination, Scrollbar, A11y]}
                  spaceBetween={0}
                  slidesPerView={1.2}
                  pagination={{ clickable: true }}
                  onSwiper={(swiper) => console.log(swiper)}
                  onSlideChange={() => console.log('slide change')}
                >
                  <SwiperSlide>
                    <div className={styles.spacing}><PhotoCard caminho='/img/cardImage1.svg' nome='MARCUS RHIEL' tipo={false} largura={400} altura={650}/></div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={styles.spacing}><PhotoCard caminho='/img/cardImage2.svg' nome='DULCE AMINOFF' tipo={false} largura={400} altura={650}/></div>
                  </SwiperSlide>
                  <SwiperSlide>
                    <div className={styles.spacing}><PhotoCard caminho='/img/cardImage3.svg' nome='RAYNA STANTON' tipo={false} largura={400} altura={650}/></div>
                  </SwiperSlide>
                </Swiper>
               </div>
            }
            <div className={styles.pAtracoesButtonBox}>
              <Link className={styles.pAtracoesButton} href='/' legacyBehavior>
                <a>MOSTRAR TODOS <span>&rarr;</span></a>
                </Link>
            </div>
        </section>
      </div>
      
      {/*Seção Ingressos*/}
      <div className='background-container'>
        <div className={styles.sectionTitle}>
          {
              repeatText('INGRESSOS ').map((text, index) => {
                if(index==1){
                  return <span className={styles.span}>{text}</span>
                }
                else if(index == 0){
                  let parts = text.split("E");
                  return <h1>{parts[1]}</h1>
                }
                else{
                  return <h1>{text}</h1>
                }
              })
            }
          </div>
          <div className="main-container">
            <div className={styles.ingressoSectionBox}>
              <HomeIngressoCard tipo='PISTA' preco={99.90}/>
              <HomeIngressoCard tipo='VIP' preco={199.90}/>
              <HomeIngressoCard tipo='CAMAROTE' preco={399.90}/>
            </div>
            { // RESPONSIVO
              <div className={styles.carrossel}>
                <Swiper
                  modules={[Navigation, Pagination, Scrollbar, A11y]}
                  spaceBetween={0}
                  slidesPerView={1.2}
                  pagination={{ clickable: true }}
                  onSwiper={(swiper) => console.log(swiper)}
                  onSlideChange={() => console.log('slide change')}
                >
                  <SwiperSlide><div className={styles.spacing}><HomeIngressoCard tipo='PISTA' preco={99.90}/></div></SwiperSlide>
                  <SwiperSlide><div className={styles.spacing}><HomeIngressoCard tipo='VIP' preco={199.90}/></div></SwiperSlide>
                  <SwiperSlide><div className={styles.spacing}><HomeIngressoCard tipo='CAMAROTE' preco={399.90}/></div></SwiperSlide>
                </Swiper>
               </div>
            }
            <div className={styles.ingressosButtonBox}>
              <Link className={styles.ingressosButton} href='/' legacyBehavior>
                <a>QUERO GARANTIR MEU INGRESSO</a>
                </Link>
            </div>
        </div>
      </div>

       {/*Seção fotos*/}

        <div className={styles.sectionTitle}>
          {
              repeatText('FOTOS ').map((text, index) => {
                if(index==1){
                  return <span className={styles.span}>{text}</span>
                }
                else{
                  return <h1>{text}</h1>
                }
              })
            }
          </div>

        <div className={styles.WrapperFotos}>
          <div className={styles.fotosContainer}>
            <Image src='/img/eventoImg1.svg' alt="Imagem do evento" width={848} height={486} />
            <Image src='/img/eventoImg2.svg' alt="Imagem do evento" width={848} height={486} />
            <Image src='/img/eventoImg3.svg' alt="Imagem do evento" width={848} height={486} />
          </div>

            { // RESPONSIVO
              <div className={styles.fotosContainerResponsivo}>
                <Image src='/img/eventoImg1.svg' alt="Imagem do evento" width={653} height={500} />
                <div className={styles.legendasBox}>
                <Image className={styles.starImg1} src='/img/star.svg' alt="Imagem de uma estrela" width={250} height={250} />
                <h1 className={styles.numeroA}>3</h1>
                <h1 className={styles.textoA}>dias</h1>
                </div>
                <Image src='/img/eventoImg2.svg' alt="Imagem do evento" width={653} height={500} />
                <div className={styles.legendasBox}>
                <Image className={styles.starImg1} src='/img/star.svg' alt="Imagem de uma estrela" width={250} height={250} />
                <h1 className={styles.numeroB}>9</h1>
                <h1 className={styles.textoB}>atrações</h1>
                </div>
                <Image src='/img/eventoImg3.svg' alt="Imagem do evento" width={653} height={500} />
                <div className={styles.legendasBox}>
                <h1 className={styles.numeroC}>21</h1>
                <h1 className={styles.textoC}>horas</h1>
                </div>
              </div>
            }

          <div className={styles.legendasContainer}>

            <div className={styles.legendasBox}>
              <h1>3</h1>
              <h2>dias</h2>
            </div>

            <Image className={styles.starImg} src='/img/star.svg' alt="Imagem de uma estrela" width={157} height={157} />

            <div className={styles.legendasBox}>
              <h1>9</h1>
              <h3>atrações</h3>
            </div>

            <Image className={styles.starImg} src='/img/star.svg' alt="Imagem de uma estrela" width={157} height={157} />

            <div className={styles.legendasBox}>
            <h1 style={{fontSize:'10em'}}>21</h1>
              <h2>horas</h2>
            </div>
          </div>
        </div>

        {/* Seção Contato */}

        <div className={styles.sectionTitle}>
          {
              repeatText('CONTATO ').map((text, index) => {
                if(index==1){
                  return <span className={styles.span}>{text}</span>
                }
                // else if(index == 0){
                //   let parts = text.split("C");
                //   return <h1>{parts[1]}</h1>
                // }
                else{
                  return <h1>{text}</h1>
                }
              })
            }
          </div>

        <div className={styles.contatoWrapper}>
            <div className={styles.contatoInfos}>

              <div>
              <Image className={styles.contatoIcon} src='/img/contatoIcons/endereco.svg' alt='icone endereço' width={50} height={66.1}></Image>
                <p>Japão, 〒106-0032 Tokyo, Minato City, Roppongi, 3 Chome−8−15 日拓ビル B1</p>
              </div>

              <div>
              <Image className={styles.contatoIcon} src='/img/contatoIcons/telefone.svg' alt='icone telefone' width={50} height={48.74}></Image>
                <p>+81 3-3403-3666</p>
              </div>

              <div>
              <Image className={styles.contatoIcon} src='/img/contatoIcons/email.svg' alt='icone email' width={50} height={39.66}></Image>
                <p>contato@meltfusiontokyo.com</p>
              </div>
            </div>
            <div className={styles.contatoMap}>
              <Image src='/img/map.svg' alt='imagem do mapa' width={628} height={486}></Image>
            </div>
        </div>
      
      <Footer />
    </>
  )
}
